services:
  preppy:
    build: .

    environment:
      - SECRET_KEY=${SECRET_KEY}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USE_SSL=${MAIL_USE_SSL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

    ports:
      - "${HOST_PORT:-5000}:5000"

    volumes:
      - ${HOST_UPLOADS_DIR}:/project/uploads
      - ${HOST_LOGS_DIR}:/project/logs
      - ${HOST_STYLES_DIR}:/project/static/css
